config/routes.rb
Rails.application.routes.draw do

  resources :re_plans do
    member do
      get 'change'
      get 'preview'
      put 'publish'
      put 'revert'
      get 'history'
      get 'copy'
      post 'duplicate'
    end
  
    resources :workflows, :controller => :re_plan_workflows, :except => [:index] do
      member do
        get 'change'
        put 'default'
        put 'add'
        put 'remove'
        get 'copy'
        post 'duplicate'
      end  
      
      resources :rules, :controller => :re_plan_workflow_rules, :except => [:index, :show] do
        collection do
          get 'help'
          get 'error'
        end
                
        member do
          put 'move_up'
          put 'move_down'
        end  
      end                                         
    end  
  end

  resources :re_workflows do
    collection do
      get 'add'
    end
    
    member do
      get 'plan'
      get 'change'
      get 'preview'
      get 'copy'
      post 'duplicate'
    end
                      
    resources :rules, :controller => :re_workflow_rules, :except => [:index, :show] do
      collection do
        get 'help'
        get 'error'
      end  
         
      member do
        put 'move_up'
        put 'move_down'
      end
    end    
  end  

  match '/re_history'           => 're_history#index'
  match '/re_history/:id'       => 're_history#show'
  match '/re_publications/:id'  => 're_publications#show'
end  

app/controllers/re_workflow_rules_controller.rb
class ReWorkflowRulesController < ApplicationController    
  helper :rules_engine 
  layout RulesEngineView::Config.layout || 'rules_engine'
  
  # before_filter :login_required
  before_filter :rules_engine_editor_access_required, :except => [:help, :error]
  before_filter :rules_engine_reader_access_required, :only => [:help, :error]
  
  before_filter do |controller|
    controller.re_load_model :re_workflow, {:param_id => :re_workflow_id, :redirect_path => :re_workflows_path}    
  end
  
  before_filter :only => [:edit, :update, :destroy, :move_up, :move_down] do |controller|
    controller.re_load_model :re_rule, {:param_id => :id, :parents => [:re_workflow], :redirect_path => :change_re_workflow_path}
  end    
  
  def help
    @rule_class = RulesEngine::Discovery.rule_class(params[:rule_class_name])
    
    if @rule_class.nil?
      flash[:error] = "#{params[:rule_class]} : class not found."
      render :error
    end
  end  
  
  def error
  end  
  
  def new
    @re_rule = ReRule.new(:re_workflow_id => @re_workflow.id, :rule_class_name => params[:rule_class_name])
    if @re_rule.rule.nil? 
      render :action => "error"
      return
    end
    
    render :action => "new"      
  end
  
  def create
    @re_rule = ReRule.new(:re_workflow_id => @re_workflow.id, :rule_class_name => params[:rule_class_name])
    if @re_rule.rule.nil?       
      render :action => "error"
      return      
    end
    
    @re_rule.rule_attributes = params
    if @re_rule.valid? && @re_rule.save
      flash[:success] = 'Rule Created.'      
    
      respond_to do |format|
        format.html do          
          redirect_to(change_re_workflow_path(@re_workflow))
        end  
        format.js do
          render :action => "update"
        end
      end
    else
      render :action => "new"
    end
  end

  def edit
    if @re_rule.rule.nil? 
      render :action => "error"
      return
    end
    
    render :action => "edit"      
  end

  def update
    if @re_rule.rule.nil? 
      render :action => "error"
      return
    end
    
    @re_rule.rule_attributes = params
    if @re_rule.valid? && @re_rule.save
      flash[:success] = 'Rule Updated.'      
      
      respond_to do |format|
        format.html do          
          redirect_to(change_re_workflow_path(@re_workflow))
        end  
        format.js do
          render :action => "update"
        end
      end
    else
      render :action => "edit"
    end
  end

  def destroy
    @re_rule.destroy
    flash[:success] = 'Rule Deleted.'

    respond_to do |format|
      format.html do
        redirect_to(change_re_workflow_path(@re_workflow))
      end  
      format.js do
        render :action => "update"
      end
    end
    
  end
  
  def move_up
    @re_rule.move_higher
    flash[:success] = 'Rule Moved Up.'      
    
    respond_to do |format|
      format.html do          
        redirect_to(change_re_workflow_path(@re_workflow))
      end  
      format.js do
        render :action => "update"
      end
    end
  end

  def move_down
    @re_rule.move_lower
    flash[:success] = 'Rule Moved Down.'      
    
    respond_to do |format|
      format.html do          
        redirect_to(change_re_workflow_path(@re_workflow))
      end  
      format.js do
        render :action => "update"
      end
    end
  end
end

app/views/re_workflow_rules/_edit.html.erb
<%#= :update_path => re_workflow_rule_path(@re_workflow, @re_rule) %>
<%#= :cancel_path => change_re_workflow_path(@re_workflow) %>

<div class="clear prepend-1 span-18">
  <h3 class="re-hdr-rule-edit"> Edit <%= @re_rule.rule.options[:display_name] %></h3>
  <div class="clear top-10"></div>

  <%= re_form_for(@re_rule, :url => update_path, :method => :post, :span => "3x13", :html => {:id => "re_rule_edit_form"}) do |f| %>
    <%= f.re_error_on "Unable To Update Rule : #{@re_rule.rule.options[:display_name]}" %>
    <%= re_whitebox do %>    
      <%= render(@re_rule.rule.options[:edit_partial], :f => f) %>
      
      <div class="clear"></div>
  	  <%= re_button_submit_green('Update', :id => "re_rule_edit_update") %>
  	  <%= re_button_link_orange('Cancel', cancel_path, :id => "re_rule_edit_cancel") %>
    <% end %>
  <% end %>
</div>  
<div class="clear"></div>

app/views/re_workflow_rules/_error.html.erb
<h2>Rule Not Found - <span class="red"><%= params[:rule_class_name].blank? ? 'param :rule_class_name missing' : params[:rule_class_name]  %></span></h2>

app/views/re_workflow_rules/_help.html.erb
<%#= :cancel_path => change_re_workflow_path(@re_workflow) %>

<div class="clear span-18">
  <h3 class="re-hdr-rule-help"> Help : <%= @rule_class.options[:display_name] %></h3>
  <div class="clear top-10"></div>

  <%= re_whitebox do %>      
  
    <%= render(@rule_class.options[:help_partial]) %>    
    
    <div class="clear"></div>
	  <%= re_button_link_red('Close', cancel_path, :id => "re_rule_help_cancel") %>
  <% end %>
</div>  
<div class="clear"></div>

app/views/re_workflow_rules/_new.html.erb
<%#= :create_path => re_workflow_rules_path(@re_workflow) %>
<%#= :cancel_path => change_re_workflow_path(@re_workflow) %>

<div class="clear prepend-1 span-18">
  <h3 class="re-hdr-rule-new"> New : <%= @re_rule.rule.options[:display_name] %></h3>
  <div class="clear top-10"></div>

  <%= re_form_for(@re_rule, :url => create_path, :method => :post, :span => "3x15", :html => {:id => "re_rule_new_form"}) do |f| %>
    <%= hidden_field_tag('rule_class_name', @re_rule.rule_class_name) %>
    <%= f.re_error_on "Unable To Create Rule : #{@re_rule.rule.options[:display_name]}" %>
    <%= re_whitebox do %>        
      <%= render(@re_rule.rule.options[:new_partial], :f => f) %>
      
      <div class="clear"></div>
  	  <%= re_button_submit_green('Create', :id => "re_rule_new_insert") %>
  	  <%= re_button_link_orange('Cancel', cancel_path, :id => "re_rule_new_cancel") %>
    <% end %>
  <% end %>
</div>  
<div class="clear"></div>

app/views/re_workflow_rules/edit.html.erb
<% set_re_breadcrumbs link_to("All Workflows", re_workflows_path, :class => "re-bc-workflow-list"), 
											link_to("View Workflows", re_workflow_path(@re_workflow), :class => "re-bc-workflow-show"), 
											link_to("Edit Workflow", change_re_workflow_path(@re_workflow), :class => "re-bc-workflow-change"), 
											'<span class="re-bc-rule-edit">Edit Rule</span>'.html_safe %>
																	
<div class="prepend-1 span-22 append-1">      
  <div class="re-infobox">
    <%= render '/re_workflow_rules/edit', :update_path => re_workflow_rule_path(@re_workflow, @re_rule),
 											 										:cancel_path => change_re_workflow_path(@re_workflow)	%>
    <div class="clear"></div>
  </div>  
</div>  
<div class="clear"></div>

app/views/re_workflow_rules/edit.js.erb
$('#re_content').html('<%=escape_javascript(render('/re_workflow_rules/edit', :update_path => re_workflow_rule_path(@re_workflow, @re_rule),
 											 																												:cancel_path => change_re_workflow_path(@re_workflow)))%>');

$('#re_rule_edit_update').closest('div.re-form-button').re_form_button(); 

$("#re_rule_edit_form").submit(function() { return false; });

$.re_unblock();
$.fancybox({ href: '#re_content'});

app/views/re_workflow_rules/error.html.erb
<% set_re_breadcrumbs link_to("All Workflows", re_workflows_path, :class => "re-bc-workflow-list"), 
											link_to("View Workflows", re_workflow_path(@re_workflow), :class => "re-bc-workflow-show"), 
											link_to("Edit Workflow", change_re_workflow_path(@re_workflow), :class => "re-bc-workflow-change"), 
											'<span class="re-bc-rule-error">Rule Error</span>'.html_safe %>

<div class="prepend-1 span-22 append-1">      
  <div class="re-infobox">
    <%= render '/re_workflow_rules/error' %>
    <div class="clear"></div>
  </div>  
</div>  
<div class="clear"></div>

app/views/re_workflow_rules/error.js.erb
<%= re_alert_js %>

$('#re_content').html('<%=escape_javascript(render('/re_workflow_rules/error'))%>');

$.re_unblock();
$.fancybox({ href: '#re_content'});          

app/views/re_workflow_rules/help.html.erb
<% set_re_breadcrumbs link_to("All Workflows", re_workflows_path, :class => "re-bc-workflow-list"), 
											link_to("View Workflows", re_workflow_path(@re_workflow), :class => "re-bc-workflow-show"), 
											link_to("Edit Workflow", change_re_workflow_path(@re_workflow), :class => "re-bc-workflow-change"), 
											'<span class="re-bc-rule-help">Rule Help</span>'.html_safe %>

<div class="prepend-3 span-22 append-1">      
  <div class="re-infobox">
    <%= render '/re_workflow_rules/help', :cancel_path => change_re_workflow_path(@re_workflow) %>
    <div class="clear"></div>
  </div>  
</div>  
<div class="clear"></div>

app/views/re_workflow_rules/help.js.erb
$('#re_content').html('<%=escape_javascript(render('/re_workflow_rules/help', :cancel_path => change_re_workflow_path(@re_workflow)))%>');

$.re_unblock();
$.fancybox({ href: '#re_content'});          

app/views/re_workflow_rules/new.html.erb
<% set_re_breadcrumbs link_to("All Workflows", re_workflows_path, :class => "re-bc-workflow-list"), 
											link_to("View Workflows", re_workflow_path(@re_workflow), :class => "re-bc-workflow-show"), 
											link_to("Edit Workflow", change_re_workflow_path(@re_workflow), :class => "re-bc-workflow-change"), 
											'<span class="re-bc-rule-new">New Rule</span>'.html_safe %>

<div class="prepend-1 span-22 append-1">      
	<div class="re-infobox">
   	<%= render '/re_workflow_rules/new', :create_path => re_workflow_rules_path(@re_workflow), :cancel_path => change_re_workflow_path(@re_workflow) %>
   	<div class="clear"></div>
	</div>  
	<div class="clear"></div>
</div>	

app/views/re_workflow_rules/new.js.erb
$('#re_content').html('<%=escape_javascript(render('/re_workflow_rules/new', :create_path => re_workflow_rules_path(@re_workflow), :cancel_path => change_re_workflow_path(@re_workflow)))%>');

$('#re_rule_new_insert').closest('div.re-form-button').re_form_button(); 

$("#re_rule_new_form").submit(function() { return false; });

$.re_unblock();
$.fancybox({ href: '#re_content'});
$.fancybox.resize();

app/views/re_workflow_rules/update.js.erb
$.fancybox.close();
$.re_unblock();

<%= re_alert_js %>

$('#re_workflow_change').html('<%=escape_javascript(render('/re_workflows/show'))%>');

$('#re_rule_change').html('<%=escape_javascript(render('/re_workflows/rule_empty', :hide => !@re_workflow.re_rules.empty?))%>');
<% @re_workflow.re_rules.each do |re_rule | %>
  $('#re_rule_change').append('<%=escape_javascript(render('/re_workflows/rule_change', :re_rule => re_rule, 
																																													:re_plan_id => 0,
																																													:delete_path => re_workflow_rule_path(@re_workflow, re_rule),
																																													:move_up_path => move_up_re_workflow_rule_path(@re_workflow, re_rule),
																																													:move_down_path => move_down_re_workflow_rule_path(@re_workflow, re_rule),
																																													:first_rule => re_rule == @re_workflow.re_rules[0], 
																																													:last_rule => re_rule == @re_workflow.re_rules[-1]))%>');
<% end %>