config/routes.rb
Rails.application.routes.draw do

  resources :re_plans do
    member do
      get 'change'
      get 'preview'
      put 'publish'
      put 'revert'
      get 'history'
      get 'copy'
      post 'duplicate'
    end
  
    resources :workflows, :controller => :re_plan_workflows, :except => [:index] do
      member do
        get 'change'
        put 'default'
        put 'add'
        put 'remove'
        get 'copy'
        post 'duplicate'
      end  
      
      resources :rules, :controller => :re_plan_workflow_rules, :except => [:index, :show] do
        collection do
          get 'help'
          get 'error'
        end
                
        member do
          put 'move_up'
          put 'move_down'
        end  
      end                                         
    end  
  end

  resources :re_workflows do
    collection do
      get 'add'
    end
    
    member do
      get 'plan'
      get 'change'
      get 'preview'
      get 'copy'
      post 'duplicate'
    end
                      
    resources :rules, :controller => :re_workflow_rules, :except => [:index, :show] do
      collection do
        get 'help'
        get 'error'
      end  
         
      member do
        put 'move_up'
        put 'move_down'
      end
    end    
  end  

  match '/re_history'           => 're_history#index'
  match '/re_history/:id'       => 're_history#show'
  match '/re_publications/:id'  => 're_publications#show'
end  

app/models/re_workflow.rb
class ReWorkflow < ActiveRecord::Base
  has_many :re_plan_workflows, :dependent => :destroy
  has_many :re_plans, :through => :re_plan_workflows, :order => 're_plan_workflows.position'
  has_many :re_rules, :foreign_key => :re_workflow_id, :dependent => :destroy, :order => :position
  
  validates_presence_of   :code
  validates_presence_of   :title
  validates_uniqueness_of :code, :case_sensitive => false, :message=>"alread taken."
  
  scope :order_code,  order('re_workflows.code ASC')
  scope :order_title, order('re_workflows.title ASC')
  
  before_save    :before_save_workflow
  before_destroy :before_destroy_workflow

  def before_save_workflow
    self.changed! if changes.detect { |change| !ignore_attributes.include?(change[0])}    
  end  
  
  def before_destroy_workflow
    re_plans.each do |re_plan|
      re_plan.changed!
    end
  end

  def code=(new_code)
    self[:code] = new_code.strip.downcase.gsub(/[^a-zA-Z0-9]+/i, '_') if new_code && new_record?
  end
  
  def publish
    { "code" => code, 
      "title" => title, 
      "description" => description,
      "rules" => re_rules.map{ | re_rule | re_rule.publish }
    }
  end  

  def revert!(rule_data)
    self.code = rule_data["code"]
    self.title = rule_data["title"]
    self.description = rule_data["description"]
    
    self.re_rules = (rule_data["rules"] || []).map { |rule| ReRule.new.revert!(rule) }
    self
  end  

  def workflow_error
    return 'rules required' if re_rules.empty?
    return 'error within rules' if re_rules.any? { | re_rule | re_rule.rule_error }    
    nil
  end

  
  def changed!
    re_plans.each do |re_plan|
      re_plan.changed!
    end
  end
  
  def has_plan? re_plan
    re_plans.include? re_plan
  end
  
  protected
    def ignore_attributes 
      [self.class.primary_key, self.class.inheritance_column, "created_at", "updated_at"]
    end
end

app/controllers/re_workflows_controller.rb
class ReWorkflowsController < ApplicationController    
  helper :rules_engine 
  layout RulesEngineView::Config.layout || 'rules_engine'
  
  # before_filter :login_required
  before_filter :rules_engine_editor_access_required,  :only => [:new, :create, :edit, :update, :destroy, :change, :copy, :duplicate]
  before_filter :rules_engine_reader_access_required,  :only => [:index, :show, :preview, :plan, :add]

  before_filter :only => [:show, :edit, :update, :destroy, :change, :preview, :plan, :copy, :duplicate] do |controller|
    controller.re_load_model :re_workflow
  end    

  def index
    @re_workflows = ReWorkflow.order_title.find(:all)
  end
  
  def show
  end

  def new
    @re_workflow = ReWorkflow.new
  end
  
  def create
    @re_workflow = ReWorkflow.new(params[:re_workflow])
    
    if @re_workflow.save
      flash[:success] = 'Workflow Created.'
      
      respond_to do |format|
        format.html do
          redirect_to(change_re_workflow_path(@re_workflow))
        end  
        format.js do
          render :action => "create"
        end
      end
    else
      render :action => "new"
    end    
  end

  def edit    
  end

  def update
    update_params = params[:re_workflow] || {}
    @re_workflow.attributes = update_params.except(:code)
    if @re_workflow.save
      flash[:success] = 'Workflow Updated.'
      
      respond_to do |format|
        format.html do          
          redirect_to(change_re_workflow_path(@re_workflow))
        end  
        format.js do
          render :action => "update"
        end
      end
    else
      render :action => "edit"
    end    
  end

  def destroy
    @re_workflow.destroy
    flash[:success] = 'Workflow Removed.'
    
    respond_to do |format|
      format.html do
        redirect_to(re_workflows_path)
      end  
      format.js do
        render :inline => "window.location.href = '#{re_workflows_path}';"
      end
    end
  end

  def change
    RulesEngine::Discovery.discover!
  end
  
  def preview
  end

  def plan
    klass = RePlanWorkflow
    klass = klass.order_plan_title
    klass = klass.by_workflow_id(@re_workflow.id)
    @re_plan_workflows = klass.paginate(:include => :re_plan, :page => params[:page] || 1, :per_page => 10)
  end

  def add
    @re_workflows = ReWorkflow.order_title.find(:all)
  end
  
  def copy
    @re_workflow_copy = ReWorkflow.new
  end

  def duplicate
    @re_workflow_copy = ReWorkflow.new
    @re_workflow_copy.revert!(@re_workflow.publish)
    @re_workflow_copy.attributes = params[:re_workflow]

    if @re_workflow_copy.save    
      flash[:success] = 'Workflow Duplicated.'
      respond_to do |format|
        format.html do
          redirect_to(change_re_workflow_path(@re_workflow_copy))
        end  
        format.js do
          render :inline => "window.location.href = '#{change_re_workflow_path(@re_workflow_copy)}';"
        end
      end
    else
       render :action => "copy"  
    end  
  end
  
end

app/views/re_workflows/_add_prepare.html.erb
<h4>
  <%= link_to("Add New Workflow", "##{re_plan_id}", :id => "re_workflow_new", :class => "re-menu-workflow-new") %>
</h4>    
<div class="clear top-5"></div>
<h4>
	<div class="re-menu-workflow-add" id="re_menu_workflow_add_<%= re_plan_id %>">Add Existing Workflow</div>
</h4>    
<div class="clear top-5"></div>
<div id="re_workflow_add_pending">
	<div class="re-xtra-workflow-add-pending">
		Updating Workflows
	</div>	
</div>
<div id="re_workflow_add">
</div>

app/views/re_workflows/_add_update.html.erb
<% if @re_workflows.empty? %>
	<h6 class="left-50 red"><em>No Workflows to Add</em></h6>
<% else %>
	<% @re_workflows.each do |re_workflow| %>
		<div class="clear top-2"></div>
		<h6>	
			<%= link_to(re_workflow.title, "##{re_workflow.id}", :class => "re-menu-workflow-add-link") %>
			<a href="#<%= re_workflow.id %>" class="re-xtra-workflow-preview float-right">
				<div class="re-xtra-workflow-preview"></div>
			</a>	
		</h6>	

		<hr/>

		<div style="display:none">
		  <%= re_form_for(re_workflow, :url => '#', :html => {:method => :put, :id => "re_workflow_add_form_#{re_workflow.id}"}) do |f| %>
		  <% end %>  
		</div>  				
	<% end %>
<% end %>
	

app/views/re_workflows/_index.html.erb
<% local_hide = local_assigns[:hide] && hide  %>
<% re_workflow_error = re_workflow.workflow_error %>

<div id="re_workflow_index_<%= re_workflow.id %>" style="<%= local_hide ?  'display:none' : '' %>">
  <div class="re-infobox">
    <div class="span-14">
      <h4 class="re-sts-workflow-<%= re_workflow_error.blank? ? 'valid' : 'verify' %>">
				<%=h re_workflow.title %>				
				<span class="re-code blue">(<%=h re_workflow.code%>)</span>
			</h4>
    </div>  
    <div class="span-5 last">
			<% if rules_engine_editor? %>
       	<h4 class="float-right"><%= link_to("Edit", change_re_workflow_path(re_workflow), :class => "re-menu-workflow-change") %></h4>
			<% end %>
			<h4 class="float-right"><%= link_to("View", re_workflow_path(re_workflow), :class => "re-menu-workflow-show") %></h4>    
    </div>  

		<div class="clear top-5"></div>
		<hr/>

    <div class="span-1">
			<a href="#<%= re_workflow.id %>" class="re-xtra-workflow-preview">
				<div class="re-xtra-workflow-preview"></div>
			</a>	
    </div>
    <div class="span-14">
			<p><%=h re_workflow.description%></p>
    </div>  
		<div class="span-4 last">
      <% if re_workflow_error.blank? %>
				<em class="float-right top-5 re-sts-workflow-valid">Valid</em>
      <% else %>
        <em class="float-right top-5 red"><%= re_workflow_error %></em>
      <% end %>
		</div>
    <div class="clear"></div>
  </div>  
	
	<div class="clear top-5"></div>  
</div>

app/views/re_workflows/_new.html.erb
<%#= :create_path => re_plan_workflows_path(@re_plan) %>
<%#= :cancel_path => change_re_plan_path(@re_plan) %>

<div class="clear prepend-1 span-18">
  <h3 class="re-hdr-workflow-new">New Workflow</h3>
  <div class="clear top-10"></div>
  
  <%= re_form_for(@re_workflow, :url => create_path, :method => :post, :span => "3x13", :html => {:id => "re_workflow_new_form"}) do |f| %>
    <%= f.re_error_on "Unable To Create Workflow" %>
    <%= re_whitebox do %>    
      <%= f.text_field(:code, :required => true, :hint => "must be unique") %>
      <%= f.text_field(:title, :required => true) %>
      <%= f.text_area(:description) %>
    
      <div class="clear"></div>
  	  <%= re_button_submit_green('Insert', :id => "re_workflow_new_insert") %>
  	  <%= re_button_link_orange('Cancel', cancel_path, :id => "re_workflow_new_cancel") %>
    <% end %>
  <% end %>
</div>  
<div class="clear"></div>

app/views/re_workflows/_preview.html.erb
<div class="span-22">
	<div class="span-2">
		<div class="re-xtra-workflow-title-single"><span>Workflow</span></div>
	</div>
	<div class="span-20 last">
		<div class="re-infobox">    
			<%= render '/re_workflows/show' %>    
			<div class="clear"></div>
		</div>
			
		<div class="span-2 pull-1">
			<div class="re-xtra-rule-title-plural"><span>Rules</span></div>
		</div>	
		<div class="span-19 last">
			<div class="re-infobox no-top">    
				<%= render '/re_workflows/rule_empty', :hide => !@re_workflow.re_rules.empty? %>

				<% @re_workflow.re_rules.each_with_index do |re_rule, rule_index | %>
					<%= render '/re_workflows/rule_preview', :re_rule => re_rule,
																								:new_row => (rule_index != 0 && (rule_index % 2) == 0), 
																								:last_rule => re_rule == @re_workflow.re_rules[-1] %>
		    <% end %>
				<div class="clear"></div>
		  </div>  
		</div>
	</div>
	<div class="clear"></div>
	<%= re_button_link_orange('Close', re_plans_path, :id => "re_workflow_preview_close") %>
	<div class="clear top-10"></div>
</div>  

app/views/re_workflows/_rule_empty.html.erb
<% local_hide = local_assigns[:hide] && hide  %>

<div id="re_rule_empty" style="<%= local_hide ?  'display:none' : '' %>">
  <div class="re-redbox-header"><h4 class="white">No Workflow Rules</h4></div>   
  <div class="re-redbox no-top">
    <div class="clear top-5">
      <h5>Add Rules to the Workflow.</h5>
			<p class="left-10">Rules are the unique decisions factors.</p> 
    </div>  
  </div>
	<div class="clear"></div>      
</div>  

app/views/re_workflows/_rule_show.html.erb
<% re_rule_error = re_rule.rule_error %>
<% local_last_rule = local_assigns[:last_rule] && last_rule  %>

<div class="<%= re_rule_error.blank? ? 're-bluebox' : 're-redbox' %>">
  <h4 class="float-left re-sts-rule-<%= re_rule_error.blank? ? 'valid' : 'verify' %>"><%=h re_rule.title %></h4>
  <div class="float-right">
		<!-- NO ACTIONS ON THE RULE	 -->
		<%= link_to("<span>Help</span>".html_safe, "##{re_plan_id}|#{@re_workflow.id}|#{re_rule.rule_class_name}", :class => "re-list-rule-help") %>
  </div>
  <div class="clear"></div>    
</div>
<div class="<%= re_rule_error.blank? ? 're-bluebox' : 're-redbox' %> no-top"> 
	<div class="span-7">
     <p class="top-5">
			<span class="re-code blue"><%=h re_rule.rule.options[:display_name]%>:</span>
			<%=h re_rule.summary %>
		</p>	
	</div>      
	<div class="span-5 float-right">
		<div class="float-right red smalltext right-5">
			<%=h re_rule_error %>
		</div>
		<div class="top-5 clear"></div>
		<% re_rule.rule.expected_outcomes.each do |expected_outcome| %>
			<% if expected_outcome[:outcome] == RulesEngine::Rule::Outcome::STOP_SUCCESS %>	
				<div class="re-xtra-rule-stop-success"><%= expected_outcome[:title] || 'Stop Success' %></div>
			<% elsif expected_outcome[:outcome] == RulesEngine::Rule::Outcome::STOP_FAILURE %>	
				<div class="re-xtra-rule-stop-failure"><%= expected_outcome[:title] || 'Stop Failure' %></div>
			<% elsif expected_outcome[:outcome] == RulesEngine::Rule::Outcome::START_WORKFLOW %>	
				<div class="re-xtra-rule-start-workflow"><%= expected_outcome[:title] || 'Start Workflow' %></div>
			<% elsif expected_outcome[:outcome] == RulesEngine::Rule::Outcome::NEXT %>
				<div class="re-xtra-rule-continue"><%= expected_outcome[:title] || 'Continue' %></div>
			<% end %>        
		<% end %>  
	</div>
	<div class="clear"></div>    
</div>
<div class="clear"></div>    

<% unless local_last_rule %>
  <div class="prepend-8 span-2"><div class="re-xtra-rule-next-down"></div></div>
	<div class="clear"></div>  
<% end %>

app/views/re_workflows/_show.html.erb
<% re_workflow_error = @re_workflow.workflow_error %>

<div class="span-19">
	<h4 class="re-sts-workflow-<%= re_workflow_error.blank? ? 'valid' : 'verify' %>">
		<%=h @re_workflow.title %>
		<span class="re-code blue">(<%=h @re_workflow.code%>)</span>
	</h4>
</div>  

<div class="clear top-5"></div>
<hr/>

<div class="span-14 prepend-1">
	<p><%=h @re_workflow.description%></p>
</div>  
<div class="span-4 last">
	<% if re_workflow_error.blank? %>
		<em class="float-right top-5 re-sts-workflow-valid">Valid</em>
	<% else %>
		<em class="float-right top-5 re-sts-workflow-verify"><%= re_workflow_error %></em>
	<% end %>
</div>

app/views/re_workflows/add.html.erb
<% set_re_javascript_include ['rules_engine/re_workflow_add', 'rules_engine/re_workflow_preview'] %>
<% set_re_breadcrumbs link_to("All Workflows", re_workflows_path, :class => "re-bc-workflow-list"), 
											'<span class="re-bc-plan-list">Add Workflow</span>'.html_safe %>

<div class="prepend-1 span-22 append-1">      
  <div class="re-infobox">
    <%= render '/re_workflows/add_prepare', :re_plan_id => "0" %>
    <div class="clear top-5"></div>
  </div>  
</div>  
<div class="clear"></div>

app/views/re_workflows/change.html.erb
<% set_re_javascript_include 'rules_engine/re_workflow_change' %>
<% set_re_breadcrumbs link_to("All Workflows", re_workflows_path, :class => "re-bc-workflow-list"), 
											'<span class="re-bc-workflow-change">Edit Workflow</span>'.html_safe %>

<div class="span-2">
 	<div class="re-xtra-workflow-title-single"><span>Workflow</span></div>
</div>
<div class="span-20 border">  
	<div class="re-infobox">
		<div id="re_workflow_change">
	  	<%= render '/re_workflows/show' %>
		</div>
		<div class="clear"></div>
	</div>	

	<div class="span-2 pull-1">
	 	<div class="re-xtra-rule-title-plural"><span>Rules</span></div>
	</div>	
	<div class="span-19 last">
 		<div class="re-infobox no-top">
			<div id="re_rule_change">
		    <%= render '/re_workflows/rule_empty', :hide => !@re_workflow.re_rules.empty? %> 

	      <% @re_workflow.re_rules.each do |re_rule | %>
	        <%= render '/re_workflows/rule_change', :re_rule => re_rule, 
																									:re_plan_id => 0,
																									:delete_path => re_workflow_rule_path(@re_workflow, re_rule),
																									:move_up_path => move_up_re_workflow_rule_path(@re_workflow, re_rule),
																									:move_down_path => move_down_re_workflow_rule_path(@re_workflow, re_rule),
																									:first_rule => re_rule == @re_workflow.re_rules[0], 
																									:last_rule => re_rule == @re_workflow.re_rules[-1] %>
	      <% end %>
			</div>	
   		<div class="clear"></div>
    </div>    
	</div>
</div>
<div class="span-8 last">      
	<div class="clear top-5"></div>

	<h4>
		<%= link_to("View Workflow", re_workflow_path(@re_workflow), :class => "re-menu-workflow-show") %>
	</h4>
	<div class="clear top-5"></div>

	<h4>
		<%= link_to("Copy Workflow", "#0|#{@re_workflow.id}", :id => "re_workflow_copy", :class => "re-menu-workflow-copy") %>
	</h4>
	<div class="clear top-5"></div>
	
	<hr/>
	<div class="clear top-5"></div>
	
	<%= render '/re_workflows/menu', :re_plan_id => 0, 
																		:view_path => re_workflow_path(@re_workflow),
	 																	:delete_path => re_workflow_path(@re_workflow)%>  
</div>  

app/views/re_workflows/edit.js.erb
$('#re_content').html('<%=escape_javascript(render('/re_workflows/edit', :update_path => re_workflow_path(@re_workflow), :cancel_path => change_re_workflow_path(@re_workflow)))%>');

$('#re_workflow_edit_update').closest('div.re-form-button').re_form_button(); 

$("#re_workflow_edit_form").submit(function() { return false; });

$.re_unblock();
$.fancybox({ href: '#re_content'});

$('#re_workflow_title').focus();

app/views/re_workflows/index.html.erb
<% set_re_javascript_include ['rules_engine/re_workflow_preview', 'rules_engine/re_workflow_new', 'rules_engine/re_history_index', 'rules_engine/re_history_show'] %>
<% set_re_breadcrumbs_right link_to("All Workflows", re_workflows_path, :class => "re-bc-workflow-list"),
														link_to("<em>All Plans</em>".html_safe, re_plans_path, :class => "re-bc-plan-list blue")%>

<div class="span-2">
 	<div class="re-xtra-workflow-title-plural"><span>Workflows</span></div>
</div>
<div class="span-20 border">
	<div class="prepend-1">
  	<%= render '/re_workflows/empty', :hide => !@re_workflows.empty? %>
	</div>

  <div id="re_workflow_index">
	  <% @re_workflows.each do | re_workflow | %>
	    <%= render '/re_workflows/index', :re_workflow => re_workflow %>	  	
	  <% end %>  
	</div>
</div>  

<div class="span-8 last">      
	<div class="clear top-5"></div>
	
	<% if rules_engine_editor?%>
		<h4>
			<%= link_to("New Workflow", new_re_workflow_path, :id => "re_workflow_new", :class => "re-menu-workflow-new") %>
		</h4>	
		<div class="clear top-5"></div>

		<div class="clear top-20"></div>
		<hr/>
		<div class="clear top-5"></div>
	<% end %>
	
	<%= render '/re_history/index_prepare', :re_plan_id => 0 %>
	<div class="clear top-5"></div>    
</div>  

app/views/re_workflows/plan.html.erb
<% set_re_javascript_include ['rules_engine/re_workflow_plan', 'rules_engine/re_plan_preview'] %>
<% set_re_breadcrumbs link_to("All Workflows", re_workflows_path, :class => "re-bc-workflow-list"), 
											link_to("View Workflow", re_workflow_path(@re_workflow), :class => "re-bc-workflow-show"), 	
											'<span class="re-bc-plan-list">Plans</span>'.html_safe %>

<div class="prepend-1 span-22 append-1">      
  <div class="re-infobox">
    <%= render '/re_workflows/plan_prepare' %>
    <div class="clear top-5"></div>
  </div>  
</div>  
<div class="clear"></div>

app/views/re_workflows/show.html.erb
<% set_re_javascript_include ['rules_engine/re_workflow_show', 'rules_engine/re_workflow_preview', 'rules_engine/re_workflow_plan', 'rules_engine/re_plan_preview'] %>
<% set_re_breadcrumbs link_to("All Workflows", re_workflows_path, :class => "re-bc-workflow-list"), '<span class="re-bc-workflow-show">View Workflow</span>'.html_safe %>

<div class="span-2">
 	<div class="re-xtra-workflow-title-single"><span>Workflow</span></div>
</div>
<div class="span-20 border">  
	<div class="re-infobox">
		<%= render '/re_workflows/show' %>    
		<div class="clear"></div>
	</div>	

	<div class="span-2 pull-1">
	 	<div class="re-xtra-rule-title-plural"><span>Rules</span></div>
	</div>	
	<div class="span-19 last">
 		<div class="re-infobox no-top">    	
			<%= render '/re_workflows/rule_empty', :hide => !@re_workflow.re_rules.empty? %>

    	<% @re_workflow.re_rules.each do |re_rule | %>
      	<%= render '/re_workflows/rule_show', :re_plan_id => 0,
																							:re_rule => re_rule, 
																							:last_rule => re_rule == @re_workflow.re_rules[-1] %>
      <% end %>
   		<div class="clear"></div>
		</div>	
  </div>
</div>  
<div class="span-8 last">      
	<div class="top-5"></div>
	
	<% if rules_engine_editor? %>
		<h4>
			<%= link_to("Edit Workflow", change_re_workflow_path(@re_workflow), :class => "re-menu-workflow-change") %>
		</h4>	
		<div class="clear top-5"></div>
		
		<hr/>
		<div class="clear top-5"></div>

	<% end %>

	<%= render :partial => '/re_workflows/plan_prepare' %>
	<div class="clear"></div>    
	
</div>

<div class="clear"></div>