config/routes.rb
Rails.application.routes.draw do

  resources :re_plans do
    member do
      get 'change'
      get 'preview'
      put 'publish'
      put 'revert'
      get 'history'
      get 'copy'
      post 'duplicate'
    end
  
    resources :workflows, :controller => :re_plan_workflows, :except => [:index] do
      member do
        get 'change'
        put 'default'
        put 'add'
        put 'remove'
        get 'copy'
        post 'duplicate'
      end  
      
      resources :rules, :controller => :re_plan_workflow_rules, :except => [:index, :show] do
        collection do
          get 'help'
          get 'error'
        end
                
        member do
          put 'move_up'
          put 'move_down'
        end  
      end                                         
    end  
  end

  resources :re_workflows do
    collection do
      get 'add'
    end
    
    member do
      get 'plan'
      get 'change'
      get 'preview'
      get 'copy'
      post 'duplicate'
    end
                      
    resources :rules, :controller => :re_workflow_rules, :except => [:index, :show] do
      collection do
        get 'help'
        get 'error'
      end  
         
      member do
        put 'move_up'
        put 'move_down'
      end
    end    
  end  

  match '/re_history'           => 're_history#index'
  match '/re_history/:id'       => 're_history#show'
  match '/re_publications/:id'  => 're_publications#show'
end  

app/models/re_plan.rb
class RePlan < ActiveRecord::Base    
  has_many :re_plan_workflows, :dependent => :destroy
  has_many :re_workflows, :through => :re_plan_workflows, :order => 're_plan_workflows.position'
  
  PLAN_STATUS_DRAFT      = 0
  PLAN_STATUS_CHANGED    = 1
  PLAN_STATUS_PUBLISHED  = 2
  PLAN_STATUS_REVERTED   = 3
  
  validates_presence_of   :code
  validates_presence_of   :title
  validates_uniqueness_of :code, :case_sensitive => false, :message=>"alread taken."
  
  scope :order_code,  order('code ASC')
  scope :order_title, order('title ASC')
  
  before_create :before_create_plan
  before_save :before_save_plan

  def before_create_plan
    self.plan_status = PLAN_STATUS_DRAFT
  end  

  def before_save_plan
    if (plan_status == PLAN_STATUS_REVERTED)
      self.plan_status = PLAN_STATUS_PUBLISHED
    elsif changes.detect { |change| !ignore_attributes.include?(change[0])}  
      self.changed!(false) 
    end  
  end  

  def code=(new_code)
    self[:code] = new_code.strip.downcase.gsub(/[^a-zA-Z0-9]+/i, '_') if new_code && new_record?
  end
  
  def publish
    data = { 
      "code" => code, 
      "title" => title, 
      "description" => description,
      "workflow" => re_workflows.empty? ? '' : re_workflows[0].code,
    }
    re_workflows.each_with_index do | re_workflow, index | 
      data["workflow_#{re_workflow.code}"] = re_workflow.publish 

      if re_workflows[-1] == re_workflow
        data["workflow_#{re_workflow.code}"]["next_workflow"] = ''
      else  
        data["workflow_#{re_workflow.code}"]["next_workflow"] = re_workflows[index+1].code
      end  
    end
    data
  end  

  def revert!(rule_data)
    self.plan_status = RePlan::PLAN_STATUS_REVERTED
    self.code = rule_data["code"]
    self.title = rule_data["title"]
    self.description = rule_data["description"]
    
    orig_re_workflows = []
    workflow_data = rule_data["workflow_#{rule_data["workflow"]}"]
    while (workflow_data && orig_re_workflows.length < 500)
      workflow_code = workflow_data["code"]
      re_workflow = ReWorkflow.find_by_code(workflow_code) || ReWorkflow.new
      re_workflow.revert!(workflow_data)
      orig_re_workflows << re_workflow
      
      next_workflow = workflow_data["next_workflow"]
      workflow_data = next_workflow.blank? ? nil : rule_data["workflow_#{next_workflow}"]
    end  
    
    self.re_workflows = orig_re_workflows
    self
  end  

  def add_workflow re_workflow
    return false if self.re_workflows.include?(re_workflow)
    self.re_workflows << re_workflow 
    changed!
    true
  end

  def remove_workflow re_workflow
    return false unless self.re_workflows.include?(re_workflow)
    self.re_workflows.delete(re_workflow)
    changed!
    true
  end  
  
  
  def default_workflow= re_workflow
    return if self.re_workflows.empty? || self.re_workflows[0] == re_workflow
    re_plan_workflow = re_plan_workflows.detect { | re_plan_workflow | re_plan_workflow.re_workflow_id == re_workflow.id}
    return unless re_plan_workflow

    re_plan_workflow.move_to_top
    
    self.re_plan_workflows(true)
    self.re_workflows(true)
    
    changed!
  end
  
  def default_workflow
    self.re_workflows.empty? ? nil : self.re_workflows[0]
  end
  
  def plan_error
    return 'workflows req\'d' if re_workflows.empty?
    return 'workflow error' if re_workflows.any? { | re_workflow | re_workflow.workflow_error }    
    nil
  end

  def published!
    self.plan_status = PLAN_STATUS_PUBLISHED
    self.save!
  end

  def changed!(update = true)
    if self.plan_status == PLAN_STATUS_PUBLISHED
      self.plan_status = PLAN_STATUS_CHANGED
      self.save! if update
    end  
  end
  
  protected
    def ignore_attributes 
      [self.class.primary_key, self.class.inheritance_column, "plan_status", "plan_version", "created_at", "updated_at"]
    end
end

app/controllers/re_plans_controller.rb
class RePlansController < ApplicationController    
  helper :rules_engine 
  layout RulesEngineView::Config.layout || 'rules_engine'

  # before_filter :login_required
  before_filter :rules_engine_editor_access_required,  :only => [:new, :create, :edit, :update, :destroy, :change, :publish, :revert, :copy, :duplicate]
  before_filter :rules_engine_reader_access_required,  :only => [:index, :show, :preview, :history]

  before_filter :only => [:show, :edit, :update, :destroy, :change, :preview, :publish, :revert, :history, :copy, :duplicate] do |controller|
    controller.re_load_model :re_plan
  end    

  def index    
    klass = RePlan
    @re_plans = klass.order_title
    @re_plans = klass.find(:all)
  end

  def show
  end

  def new
    @re_plan = RePlan.new
  end
  
  def create
    @re_plan = RePlan.new(params[:re_plan])
    
    if @re_plan.save
      flash[:success] = 'Plan Created.'
      
      respond_to do |format|
        format.html do
          redirect_to(change_re_plan_path(@re_plan))
        end  
        format.js do
          render :action => "create"
        end
      end
    else
      render :action => "new"
    end    
  end

  def edit    
  end

  def update
    update_params = params[:re_plan] || {}
    @re_plan.attributes = update_params.except(:code)
    if @re_plan.save
      flash[:success] = 'Plan Updated.'
      
      respond_to do |format|
        format.html do          
          redirect_to(change_re_plan_path(@re_plan))
        end  
        format.js do
          render :action => "update"
        end
      end
    else
      render :action => "edit"
    end    
  end

  def destroy
    RulesEngine::Publish.publisher.remove(@re_plan.code)
    # Remove the runner history ???
    @re_plan.destroy
    flash[:success] = 'Plan Deleted.'
    
    respond_to do |format|
      format.html do
        redirect_to(re_plans_path)
      end  
      format.js do
        render :inline => "window.location.href = '#{re_plans_path}';"
      end
    end
  end

  def change
  end
  
  def preview
  end

  def publish
    if params['tag'].blank?
      flash[:error] = 'Tag Required.'
    else  
      @re_plan.plan_version = RulesEngine::Publish.publisher.publish(@re_plan.code, params['tag'], @re_plan.publish)
      @re_plan.plan_status = RePlan::PLAN_STATUS_PUBLISHED
      @re_plan.save
      flash[:success] = 'Plan Published.'
    end  
  
    respond_to do |format|
      format.html do
        redirect_to(change_re_plan_path(@re_plan))
      end  
      format.js do
        render :action => "update"
      end
    end
  end

  def revert
    plan = RulesEngine::Publish.publisher.get(@re_plan.code)    
    if plan.nil?
      flash[:error] = 'Cannot Find Published Plan.'
    else
      @re_plan.revert!(plan)
      @re_plan.save!
      flash[:success] = 'Changes Discarded.'
    end  
    
    respond_to do |format|
      format.html do
        redirect_to(change_re_plan_path(@re_plan))
      end  
      format.js do
        render :action => "update"
      end
    end
  end
  
  def history
    @re_history = RulesEngine::Process.runner.history(@re_plan.code, :page => params[:page] || 1, :per_page => 5)    
  end

  def copy
    @re_plan_copy = RePlan.new
  end

  def duplicate
    @re_plan_copy = RePlan.new
    @re_plan_copy.revert!(@re_plan.publish)
    @re_plan_copy.attributes = params[:re_plan]

    if @re_plan_copy.save    
      flash[:success] = 'Plan Duplicated.'
      respond_to do |format|
        format.html do
          redirect_to(change_re_plan_path(@re_plan_copy))
        end  
        format.js do
          render :inline => "window.location.href = '#{change_re_plan_path(@re_plan_copy)}';"
        end
      end
    else
       render :action => "copy"  
    end  
  end
end

app/views/re_plans/_copy.html.erb
<div class="clear prepend-1 span-18">
  <h3 class="re-hdr-plan-copy"> Copy Plan : <%=h @re_plan.title %></h3>
  <div class="clear top-10"></div>
  
  <%= re_form_for(@re_plan_copy, :url => duplicate_re_plan_path(@re_plan), :method => :post, :span => "3x13", :html => {:id => "re_plan_copy_form"}) do |f| %>
    <%= f.re_error_on "Unable To Duplicated Plan" %>
    <%= re_whitebox do %>    
      <%= f.text_field(:code, :required => true, :hint => "must be unique") %>
      <%= f.text_field(:title, :required => true) %>
      <%= f.text_area(:description) %>
    
      <div class="clear"></div>
  	  <%= re_button_submit_green('Duplicate', :id => "re_plan_copy_duplicate") %>
  	  <%= re_button_link_orange('Cancel', change_re_plan_path(@re_plan), :id => "re_plan_copy_cancel") %>
    <% end %>
  <% end %>
</div>  
<div class="clear"></div>

app/views/re_plans/_edit.html.erb
<div class="clear prepend-1 span-18">
  <h3 class="re-hdr-plan-edit">Edit Details</h3>
  <div class="clear top-10"></div>
  
  <%= re_form_for(@re_plan, :url => re_plan_path(@re_plan), :method => :post, :span => "3x13", :html => {:id => "re_plan_edit_form"}) do |f| %>
    <%= f.re_error_on "Unable To Update Plan" %>
    <%= re_whitebox do %>    
      <%= re_form_text("Code", @re_plan.code, :span => "3x13", :hint => "<strong>NOTE :</strong> the plan code cannot be changed".html_safe) %>
      <div class="clear top-5"></div>
      
      <%= f.text_field(:title, :required => true) %>
      <%= f.text_area(:description) %>
    
      <div class="clear"></div>
  	  <%= re_button_submit_green('Update', :id => "re_plan_edit_update") %>
  	  <%= re_button_link_orange('Cancel', change_re_plan_path(@re_plan), :id => "re_plan_edit_cancel") %>
    <% end %>
  <% end %>
</div>  
<div class="clear"></div>

app/views/re_plans/_new.html.erb
<div class="clear prepend-1 span-18">
  <h3 class="re-hdr-plan-new"> New Plan</h3>
  <div class="clear top-10"></div>
  
  <%= re_form_for(@re_plan, :url => re_plans_path, :method => :post, :span => "3x13", :html => {:id => "re_plan_new_form"}) do |f| %>
		<%= re_error_on(@re_plan, "Unable To Create Plan") %>    
    <%= re_whitebox do %>    
      <%= f.text_field(:code, :required => true, :hint => "must be unique") %>
      <%= f.text_field(:title, :required => true) %>
      <%= f.text_area(:description) %>
    
      <div class="clear"></div>
  	  <%= re_button_submit_green('Insert', :id => "re_plan_new_insert") %>
  	  <%= re_button_link_orange('Cancel', re_plans_path, :id => "re_plan_new_cancel") %>
    <% end =%>
  <% end =%>
</div>  
<div class="clear"></div>

app/views/re_plans/_preview.html.erb
<div class="span-22">
	<div class="span-1">
		<div class="re-xtra-plan-title-single"><span>Plans</span></div>
	</div>	
	<div class="span-21 last">
 		<%= render '/re_plans/show' %>

		<% @re_plan.re_workflows.each_with_index do |re_workflow, workflow_index | %>
			<div class="span-2 pull-1">
				<% if workflow_index == 0 %>
			 		<div class="re-xtra-workflow-title-single"><span>Workflow</span></div>
				<% else %>
					&nbsp;
				<% end %>
			</div>
			<div class="span-20 last">
				<div class="re-infobox <%= @re_plan.re_workflows[0] == re_workflow ?  'no-top' : '' %>"> 
		  		<%= render '/re_plans/workflow_preview', :re_workflow => re_workflow  %>    
					<div class="clear"></div>
				</div>
			
				<div class="span-2 pull-1">
					<% if workflow_index == 0 %>
				 		<div class="re-xtra-rule-title-plural"><span>Rules</span></div>
					<% else %>
						&nbsp;
					<% end %>
				</div>	
				<div class="span-19 last">
				  <div class="re-infobox no-top">    
						<%= render '/re_workflows/rule_empty', :hide => !re_workflow.re_rules.empty? %>

				    <% re_workflow.re_rules.each_with_index do |re_rule, rule_index | %>
				      <%= render '/re_workflows/rule_preview', :re_rule => re_rule,
																										:new_row => (rule_index != 0 && (rule_index % 2) == 0), 
																										:last_rule => re_rule == re_workflow.re_rules[-1] %>
				    <% end %>
						<div class="clear"></div>
				  </div>  
				</div>
			<% end %>	
		</div>	
	</div>
	<div class="clear"></div>
	<%= re_button_link_orange('Close', re_plans_path, :id => "re_plan_preview_close") %>
	<div class="clear top-10"></div>
</div>  

app/views/re_plans/_workflow_preview.html.erb
<% re_workflow_error = re_workflow.workflow_error %>

<div class="span-19">
	<h4 class="re-sts-workflow-<%= re_workflow_error.blank? ? 'valid' : 'verify' %>">
		<%=h re_workflow.title %>
		<span class="re-code blue">(<%=h re_workflow.code%>)</span>
	</h4>
</div>  

<div class="clear top-5"></div>
<hr/>

<div class="span-13 prepend-1">
	<p><%=h re_workflow.description%></p>
</div>  
<div class="span-5 last">
	<% if re_workflow_error.blank? %>
		<em class="float-right top-5 re-sts-workflow-valid">Valid</em>
	<% else %>
		<em class="float-right top-5 re-sts-workflow-verify"><%= re_workflow_error %></em>
	<% end %>
</div>

app/views/re_plans/_workflow_show.html.erb
<% re_workflow_error = re_workflow.workflow_error %>
<% default_workflow = re_workflow == re_plan.default_workflow %>
<% last_workflow = re_workflow == re_plan.re_workflows[-1]  %>

<div class="<%= re_workflow_error.blank? ? 're-bluebox' : 're-redbox' %>">
	<div class="clear top-2"></div>    
 	<h4 class="float-left re-sts-workflow-<%= re_workflow_error.blank? ? 'valid' : 'verify' %>">
		<%=h re_workflow.title %>
		<span class="re-code blue">(<%=h re_workflow.code%>)</span>
	</h4>
	<div class="float-right">
		<!-- NO ACTIONS ON THE RULE	 -->
		<div class="float-right re-list-workflow-is-default<%= default_workflow ? '' : '-off' %>"><span>Default</span></div>
			<%= link_to("<span>Show</span>".html_safe, re_plan_workflow_path(re_plan, re_workflow), :class => "re-list-workflow-show") %>
  		</div>
  	<div class="clear top-2"></div>    
	<hr/>
	<a href="#<%= re_workflow.id %>" class="re-xtra-workflow-preview float-left">
		<div class="re-xtra-workflow-preview"></div>
	</a>	
	<p class="float-left left-5">
		<%=h re_workflow.description %>&nbsp;
	</p>
	<em class="float-right top-2 right-5 re-sts-workflow-<%= re_workflow_error.blank? ? 'valid' : 'verify' %>"><%= re_workflow_error.blank? ? 'Valid' : re_workflow_error %></em>
  <div class="clear"></div>    	
</div>          

<% unless last_workflow %>
  <div class="clear top-5"></div>
	<hr/>
	<div class="clear top-5"></div>
<% end %>

app/views/re_plans/copy.html.erb
<% set_re_breadcrumbs link_to("All Plans", re_plans_path, :class => "re-bc-plan-list"), 
											link_to("Edit Plan", change_re_plan_path(@re_plan), :class => "re-bc-plan-change"), 
											'<span class="re-bc-plan-copy">Copy Plan</span>'.html_safe %>

<div class="prepend-1 span-22 append-1">      
  <div class="re-infobox">
    <%= render 'copy' %>
    <div class="clear top-5"></div>
  </div>  
</div>  
<div class="clear"></div>

app/views/re_plans/history.html.erb
<% set_re_javascript_include ['rules_engine/re_history_index'] %>
<% set_re_breadcrumbs link_to("All Plans", re_plans_path, :class => "re-bc-plan-list"), 
										  link_to("Show Plan", re_plan_path(@re_plan), :class => "re-bc-plan-show"), 
											'<span class="re-bc-history-list">Process History</span>'.html_safe %>

<div class="prepend-1 span-22 append-1">      
  <div class="re-infobox">
    <%= render '/re_history/index_prepare', :re_plan_id => @re_plan.id %>
    <div class="clear top-5"></div>
  </div>  
</div>  
<div class="clear"></div>

app/views/re_plans/index.js.erb
$.fancybox.close();
$.re_unblock();

<%= re_alert_js %>

<% if @re_plans.empty? %>
  $('#re_plan_empty').slideDown(150, function() {
    $('#re_plan_empty').show();
  });
<% else %>  
  $('#re_plan_empty').hide();
<% end %>  


$('#re_plan_index').empty();
<% @re_plans.each do | re_plan | %>
  $('#re_plan_index').append('<%=escape_javascript(render('/re_plans/index', :re_plan => re_plan))%>');  
<% end %>  

app/views/re_plans/new.html.erb
<% set_re_breadcrumbs link_to("All Plans", re_plans_path, :class => "re-bc-plan-list"), 
															'<span class="re-bc-plan-new">New Plan</span>'.html_safe %>

<div class="prepend-1 span-22 append-1">      
  <div class="re-infobox">
    <%= render 'new' %>
    <div class="clear top-5"></div>
  </div>  
</div>  
<div class="clear"></div>

app/views/re_plans/preview.html.erb
<% set_re_breadcrumbs link_to("All Plans", re_plans_path, :class => "re-bc-plan-list"), 
															'<span class="re-bc-plan-show">Preview Plan</span>'.html_safe %>

<div class="prepend-1 span-28 append-1">      
	<%= render '/re_plans/preview' %>
</div>	

app/views/re_plans/preview.js.erb
$('#re_content').html('<%=escape_javascript(render('/re_plans/preview'))%>');

$.re_unblock();
$.fancybox({ href: '#re_content'});

app/views/re_plans/show.html.erb
<% set_re_javascript_include ['rules_engine/re_workflow_preview', 'rules_engine/re_publication_show', 'rules_engine/re_history_index', 'rules_engine/re_history_show'] %>
<% set_re_breadcrumbs link_to("All Plans", re_plans_path, :class => "re-bc-plan-list"), '<span class="re-bc-plan-show">View Plan</span>'.html_safe %>

<div class="span-22 border">      
	<div class="span-1">
		<div class="re-xtra-plan-title-single"><span>Plans</span></div>
	</div>	
	<div class="span-21 last">      
		<%= render '/re_plans/show' %>
		
		<div class="span-2 pull-1">
		 	<div class="re-xtra-workflow-title-plural"><span>Workflow</span></div>
		</div>
		<div class="span-20 last">
	 		<div class="re-infobox no-top">    	

	   		<%= render '/re_workflows/empty', :hide => !@re_plan.re_workflows.empty? %>    

		    <% @re_plan.re_workflows.each do |re_workflow | %>
		      <%= render '/re_plans/workflow_show', :re_plan => @re_plan, :re_workflow => re_workflow %>
		    <% end %>
	
				<div class="clear"></div>
			</div>	
	 	</div>  
		
	</div>
	<div class="clear"></div>
</div>  

<div class="span-8 last">      
	<div class="clear top-5"></div>

	<% if rules_engine_editor? %>
		<h4>
			<%= link_to("Edit Plan", change_re_plan_path(@re_plan), :class => "re-menu-plan-change") %>
		</h4>    		
		<div class="clear top-5"></div>

		<div class="clear top-20"></div>
		<hr/>
		<div class="clear top-5"></div>
	<% end %>

	<%= render '/re_history/index_prepare', :re_plan_id => @re_plan.id %>	
	<div class="clear top-5"></div>    
	
	<div class="clear top-20"></div>
	<hr/>
	<div class="clear top-5"></div>

	<%= render '/re_publications/show_prepare' %>
	<div class="clear"></div>
</div>

<div class="clear"></div>

app/views/re_plans/update.js.erb
$.fancybox.close();
$.re_unblock();

<%= re_alert_js %>

$('#re_plan_change').html('<%=escape_javascript(render('/re_plans/change'))%>');

$('#re_workflow_change').html('<%=escape_javascript(render('/re_workflows/empty', :hide => !@re_plan.re_workflows.empty?))%>');
<% @re_plan.re_workflows.each do |re_workflow | %>
  $('#re_workflow_change').append('<%=escape_javascript(render('/re_plans/workflow_change', :re_workflow => re_workflow))%>');
<% end %>

$('#re_plan_menu').html('<%=escape_javascript(render('/re_plans/menu'))%>');

re_plan_workflow_add_update();