config/routes.rb
Rails.application.routes.draw do

  resources :re_plans do
    member do
      get 'change'
      get 'preview'
      put 'publish'
      put 'revert'
      get 'history'
      get 'copy'
      post 'duplicate'
    end
  
    resources :workflows, :controller => :re_plan_workflows, :except => [:index] do
      member do
        get 'change'
        put 'default'
        put 'add'
        put 'remove'
        get 'copy'
        post 'duplicate'
      end  
      
      resources :rules, :controller => :re_plan_workflow_rules, :except => [:index, :show] do
        collection do
          get 'help'
          get 'error'
        end
                
        member do
          put 'move_up'
          put 'move_down'
        end  
      end                                         
    end  
  end

  resources :re_workflows do
    collection do
      get 'add'
    end
    
    member do
      get 'plan'
      get 'change'
      get 'preview'
      get 'copy'
      post 'duplicate'
    end
                      
    resources :rules, :controller => :re_workflow_rules, :except => [:index, :show] do
      collection do
        get 'help'
        get 'error'
      end  
         
      member do
        put 'move_up'
        put 'move_down'
      end
    end    
  end  

  match '/re_history'           => 're_history#index'
  match '/re_history/:id'       => 're_history#show'
  match '/re_publications/:id'  => 're_publications#show'
end  

app/controllers/re_plan_workflow_rules_controller.rb
class RePlanWorkflowRulesController < ApplicationController    
  helper :rules_engine 
  layout RulesEngineView::Config.layout || 'rules_engine'
  
  # before_filter :login_required
  before_filter :rules_engine_editor_access_required, :except => [:help, :error]
  before_filter :rules_engine_reader_access_required, :only => [:help, :error]

  before_filter do |controller|
    controller.re_load_model :re_plan, {:param_id => :re_plan_id, :redirect_path => :re_workflows_path}
  end
  
  before_filter do |controller|
    controller.re_load_model :re_workflow, {:param_id => :workflow_id, :parents => [:re_plan], :redirect_path => :re_plan_path, :validate => :has_plan?}
  end
  
  before_filter :only => [:edit, :update, :destroy, :move_up, :move_down] do |controller|
    controller.re_load_model :re_rule, {:param_id => :id, :parents => [:re_plan, :re_workflow], :redirect_path => :re_plan_workflow_path}
  end    
  
  def help
    @rule_class = RulesEngine::Discovery.rule_class(params[:rule_class_name])
    if @rule_class.nil?
      flash[:error] = "#{params[:rule_class]} : class not found."
      render :error
    else
      @rule = @rule_class.new  
    end
  end  
  
  def error
  end  
  
  def new
    @re_rule = ReRule.new(:re_workflow_id => @re_workflow.id, :rule_class_name => params[:rule_class_name])
    if @re_rule.rule.nil? 
      render :action => "error"
      return
    end
    
    render :action => "new"      
  end
  
  def create
    @re_rule = ReRule.new(:re_workflow_id => @re_workflow.id, :rule_class_name => params[:rule_class_name])
    if @re_rule.rule.nil? 
      render :action => "error"
      return      
    end
    
    @re_rule.rule_attributes = params
    if @re_rule.valid? && @re_rule.save
      flash[:success] = 'Rule Created.'      
    
      respond_to do |format|
        format.html do          
          redirect_to(change_re_plan_workflow_path(@re_plan, @re_workflow))
        end  
        format.js do
          render :action => "update"
        end
      end
    else
      render :action => "new"
    end
  end

  def edit
    if @re_rule.rule.nil? 
      render :action => "error"
      return
    end
    
    render :action => "edit"      
  end

  def update
    if @re_rule.rule.nil? 
      render :action => "error"
      return
    end
    
    @re_rule.rule_attributes = params
    if @re_rule.valid? && @re_rule.save
      flash[:success] = 'Rule Updated.'      
      
      respond_to do |format|
        format.html do          
          redirect_to(change_re_plan_workflow_path(@re_plan, @re_workflow))
        end  
        format.js do
          render :action => "update"
        end
      end
    else
      render :action => "edit"
    end
  end

  def destroy
    @re_rule.destroy
    flash[:success] = 'Rule Deleted.'

    respond_to do |format|
      format.html do
        redirect_to(change_re_plan_workflow_path(@re_plan, @re_workflow))
      end  
      format.js do
        render :action => "update"
      end
    end
    
  end
  
  def move_up
    @re_rule.move_higher
    flash[:success] = 'Rule Moved Up.'      
    
    respond_to do |format|
      format.html do          
        redirect_to(change_re_plan_workflow_path(@re_plan, @re_workflow))
      end  
      format.js do
        render :action => "update"
      end
    end
  end

  def move_down
    @re_rule.move_lower
    flash[:success] = 'Rule Moved Down.'      
    
    respond_to do |format|
      format.html do          
        redirect_to(change_re_plan_workflow_path(@re_plan, @re_workflow))
      end  
      format.js do
        render :action => "update"
      end
    end
  end
end

app/views/re_plan_workflow_rules/edit.html.erb
<% set_re_breadcrumbs link_to("All Plans", re_plans_path, :class => "re-bc-plan-list"), 
											link_to("Edit Plan", change_re_plan_path(@re_plan), :class => "re-bc-plan-change"),
											link_to("Edit Workflow", change_re_plan_workflow_path(@re_plan, @re_workflow), :class => "re-bc-workflow-change"), 
											'<span class="re-bc-rule-edit">Edit Rule</span>'.html_safe %>
																	
<div class="prepend-2 span-22 append-1">      
  <div class="re-infobox">
    <%= render '/re_workflow_rules/edit', :update_path => re_plan_workflow_rule_path(@re_plan, @re_workflow, @re_rule),
 											 										:cancel_path => change_re_plan_workflow_path(@re_plan, @re_workflow)	%>
    <div class="clear"></div>
  </div>  
</div>  
<div class="clear"></div>

app/views/re_plan_workflow_rules/edit.js.erb
$('#re_content').html('<%=escape_javascript(render('/re_workflow_rules/edit', :update_path => re_plan_workflow_rule_path(@re_plan, @re_workflow, @re_rule),
 											 																												:cancel_path => change_re_plan_workflow_path(@re_plan, @re_workflow)))%>');

$('#re_rule_edit_update').closest('div.re-form-button').re_form_button(); 

$("#re_rule_edit_form").submit(function() { return false; });

$.re_unblock();
$.fancybox({ href: '#re_content'});

app/views/re_plan_workflow_rules/error.html.erb
<% set_re_breadcrumbs link_to("All Workflows", re_workflows_path, :class => "re-bc-workflow-list"), 
											link_to("View Workflows", re_workflow_path(@re_workflow), :class => "re-bc-workflow-show"), 
											link_to("Edit Workflow", change_re_workflow_path(@re_workflow), :class => "re-bc-workflow-change"), 
											'<span class="re-bc-rule-error">Rule Error</span>'.html_safe %>

<div class="prepend-2 span-22 append-1">      
  <div class="re-infobox">
    <%= render '/re_workflow_rules/error' %>
    <div class="clear"></div>
  </div>  
</div>  
<div class="clear"></div>

app/views/re_plan_workflow_rules/error.js.erb
<%= re_alert_js %>

$('#re_content').html('<%=escape_javascript(render('/re_workflow_rules/error'))%>');

$.re_unblock();
$.fancybox({ href: '#re_content'});          

app/views/re_plan_workflow_rules/help.html.erb
<% set_re_breadcrumbs link_to("All Plans", re_plans_path, :class => "re-bc-plan-list"), 
											link_to("Edit Plan", change_re_plan_path(@re_plan), :class => "re-bc-plan-change"),
											link_to("Edit Workflow", change_re_plan_workflow_path(@re_plan, @re_workflow), :class => "re-bc-workflow-change"), 
											'<span class="re-bc-rule-help">Rule Help</span>'.html_safe %>

<div class="prepend-2 span-22 append-1">      
  <div class="re-infobox">
    <%= render '/re_workflow_rules/help', :cancel_path => change_re_plan_workflow_path(@re_plan, @re_workflow) %>
    <div class="clear"></div>
  </div>  
</div>  
<div class="clear"></div>

app/views/re_plan_workflow_rules/help.js.erb
$('#re_content').html('<%=escape_javascript(render('/re_workflow_rules/help', :cancel_path => change_re_plan_workflow_path(@re_plan, @re_workflow)))%>');

$.re_unblock();
$.fancybox({ href: '#re_content'});          

app/views/re_plan_workflow_rules/new.html.erb
<% set_re_breadcrumbs link_to("All Plans", re_plans_path, :class => "re-bc-plan-list"), 
											link_to("Edit Plan", change_re_plan_path(@re_plan), :class => "re-bc-plan-change"),
											link_to("Edit Workflow", change_re_plan_workflow_path(@re_plan, @re_workflow), :class => "re-bc-workflow-change"), 
											'<span class="re-bc-rule-new">New Rule</span>'.html_safe %>

<div class="prepend-2 span-22 append-1">      
	<div class="re-infobox">
   	<%= render '/re_workflow_rules/new', :create_path => re_plan_workflow_rules_path(@re_plan, @re_workflow), 
																					:cancel_path => change_re_plan_workflow_path(@re_plan, @re_workflow) %>
		<div class="clear"></div>
	</div>  
	<div class="clear"></div>
</div>	

app/views/re_plan_workflow_rules/new.js.erb
$('#re_content').html('<%=escape_javascript(render('/re_workflow_rules/new', :create_path => re_plan_workflow_rules_path(@re_plan, @re_workflow), 
																																						 :cancel_path => change_re_plan_workflow_path(@re_plan, @re_workflow)))%>');

$('#re_rule_new_insert').closest('div.re-form-button').re_form_button(); 

$("#re_rule_new_form").submit(function() { return false; });

$.re_unblock();
$.fancybox({ href: '#re_content'});
$.fancybox.resize();

app/views/re_plan_workflow_rules/update.js.erb
$.fancybox.close();
$.re_unblock();

<%= re_alert_js %>

$('#re_plan_change').html('<%=escape_javascript(render('/re_plans/show'))%>');

$('#re_workflow_change').html('<%=escape_javascript(render('/re_workflows/show'))%>');

$('#re_rule_change').html('<%=escape_javascript(render('/re_workflows/rule_empty', :hide => !@re_workflow.re_rules.empty?))%>');
<% @re_workflow.re_rules.each do |re_rule | %>
  $('#re_rule_change').append('<%=escape_javascript(render('/re_workflows/rule_change', :re_rule => re_rule, 
																																													:re_plan_id => @re_plan.id,
																																													:delete_path => re_plan_workflow_rule_path(@re_plan, @re_workflow, re_rule),
																																													:move_up_path => move_up_re_plan_workflow_rule_path(@re_plan, @re_workflow, re_rule),
																																													:move_down_path => move_down_re_plan_workflow_rule_path(@re_plan, @re_workflow, re_rule),
																																													:first_rule => re_rule == @re_workflow.re_rules[0], 
																																													:last_rule => re_rule == @re_workflow.re_rules[-1]))%>');
<% end %>